apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
        - name: recipe-app
          image: ptrskay3/recipe-app2:latest
          imagePullPolicy: 'Never'
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /admin/health_check
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-app-lb
spec:
  selector:
    app: recipe-app
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  externalIPs:
    - 192.168.0.25
